config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    resources :users do
      collection do
        get 'salesmen'
      end
    end
  end

  root to: 'dashboards#index'

  resources :dashboards
  resources :permissions
  resources :brands
  resources :item_bundles
  resources :discounts
  resources :contact_informations
  resources :return_slips
  resources :order_slips

  resources :attachments, only: [:destroy]

  resources :categories do
    get 'sub_categories'
  end

  resources :items do
    resources :item_inventories do
      collection do
        delete 'delete_by_bulk'
        get 'serials'
        get 'on_stock'
      end
    end

    collection do
      match 'search-available', to: "items#search_available", via: [:get, :post]
      match 'search-return', to: "items#search_return", via: [:get, :post]
      match 'search-sold', to: "items#search_sold", via: [:get, :post]
    end
  end

  resources :warehouses do
    resources :stock_sections
  end

  resources :roles do
    get 'permissions'
    get 'update_permissions'
  end

  resources :addresses do
    member do
      patch 'make_primary'
    end
  end

  resources :customers do
    resources :customer_orders do
      member do
        match 'add-item-to-order', to: "customer_orders#add_item_to", via: [:get, :post]
        match 'deduct-item-from-order', to: "customer_orders#sub_item_from", via: [:delete]
        match 'remove-item-from-order', to: "customer_orders#del_item_from", via: [:delete]
        match 'items-of', to: "customer_orders#items_of", via: [:get, :post]
      end
    end

    member do
      delete 'archive'
    end
  end

  resources :suppliers do
    member do
      get 'delete_selected'
      delete 'archive'
    end
  end

  resources :receivables do
    collection do
      get :add_deductible_entry
      get :add_breakdown
      post :del_breakdown
      post :tpl_switcher
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  include UserAccountable

  has_many :customer_addresses,
    dependent: :destroy
  has_many :addresses,
    as: :addressable,
    through: :customer_addresses
  has_many :discounts,
    as: :discountable,
    dependent: :destroy
  has_many :customer_support
  has_many :contact_informations,
    as: :contactable,
    dependent: :destroy
  has_many :bought_inventory_items,
    class_name: 'SalesDetail',
    foreign_key: :sold_to
  has_many :order_slips,
    as: :orderable

  has_one :collection_information

  belongs_to :user,
    optional: true,
    foreign_key: :salesman_id

  enum classification: {
    outright: 0,
    concessionaire: 1
  }
  enum payment_term: {
    cash_on_delivery: 0,
    _30_days: 1,
    _60_days: 2,
    _120_days: 3,
    _120_days_up: 4
  }
  enum type_of_receipt: {
    delivery_receipt: 0,
    sales_invoice: 1,
    order_sheet: 2
  }
  enum status: {
    _new: 0,
    active: 1,
    inactive: 2,
    archived: 3,
    unsaved: 4
  }

  validates :name, presence: true
  # validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  scope :saved, -> { where.not(status: :unsaved) }

  def recalculate_balance
  end

  def apply_discount(amount)
  end

  def last_invoice
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  before_action :sanitize_params, only: [:create, :update]
  before_action :set_customer, only: [:show, :edit, :update, :destroy, :archive, :save_discount]
  before_action :get_all_brands, only: [:new, :edit, :update]
  before_action :set_salesmen, only: [:new, :edit, :update]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.saved

    respond_to do |format|
      format.html
      format.json {
        render json: CustomerDatatable.new(params, view_context: view_context)
      }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    authorize Customer, :allow_add?

    if Customer.unsaved.present?
      @customer = Customer.unsaved.first
    else
      @customer = Customer.new(status: :unsaved)

      @customer.save(validate: false)

      @collection_information = CollectionInformation.new
      @collection_information.customer = @customer
      @collection_information.save(validate: false)

      log_transaction(@customer)
    end
  end

  # GET /customers/1/edit
  def edit
    authorize Customer, :allow_edit?
  end

  # POST /customers
  # POST /customers.json
  def create
    authorize Customer, :allow_add?
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    authorize Customer, :allow_edit?

    @contact_information = ContactInformation.find_by(id: collection_information_params[:contact_info])

    respond_to do |format|
      if @customer.collection_information.present?
        @customer.collection_information.set_contact(@contact_information) if @contact_information.present?
        @customer.collection_information.update(collection_information_params)
      else
        collection_info = CollectionInformation.new(collection_information_params)
        collection_info.customer = @customer
        collection_info.set_contact(@contact_information)
        collection_info.save
      end

      @customer.status = :_new if @customer.unsaved?

      if @customer.update(customer_params)
        log_transaction(@customer)

        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    authorize Customer, :allow_delete?

    @customer.destroy

    log_transaction(@customer)

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully #{params[:axn] || 'destroyed'}." }
      format.json { head :no_content }
    end
  end

  def archive
    authorize Customer, :allow_delete?

    respond_to do |format|
      @customer.archived!

      log_transaction(@customer)

      format.html { redirect_to customers_url, notice: "Customer was successfully #{params[:axn] || 'archived'}." }
      format.json { head :no_content }
    end
  end

  def save_discount
    authorize Customer, :allow_edit?

    respond_to do |format|
      format.json do
        discount = Discount.new

        discount.name = params[:name]
        discount.discount = params[:discount]
        discount.discountable = @customer

        if discount.save
          log_transaction(discount)

          render json: { discount: discount.to_json }
        else
          render status: :unprocessable_entity, json: { error_messages: discount.errors.full_messages }
        end
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_customer
    @customer = Customer.find(params[:id])
  end

  def get_all_brands
    @brands = Brand.all
  end

  def set_salesmen
    @salesmen = User.saved.joins(:roles).where(roles: { role_code: 'salesman' })

    respond_to do |format|
      format.html
      format.json { @salesmen }
    end
  end

  def sanitize_params
    sanitize_enum_params(:customer, %w(type_of_receipt classification))
    sanitize_enum_params(:collection_information, %w(credit_term))
    sanitize_formatted_numeric_params(:collection_information, %w(credit_limit), 'to_f')
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def customer_params
    params.require(:customer).permit(:id, :salesman_id, :name, :email, :classification, :owner, :type_of_receipt, :current_balance, :dist_markup, :dist_srp_markup, :admin_credit_hold, :has_bounced_cheq)
  end

  def collection_information_params
    params.require(:collection_information).permit(:counter_day, :counter_time_from, :counter_time_to, :collection_day, :collection_time_from, :collection_time_to, :credit_term, :credit_limit, :contact_info
    )
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
	def get_salesman(id)
		if id.present?
			salesman = ContactInformation.find(id)
			return salesman.name
		end
	end
end

app/views/customers/partials/_address_form_modal.html.erb
<div class="modal fade" id="address-form-modal" tabindex="-1" role="dialog" aria-labelledby="address-form-modal-label" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="address-form-modal-label">Address Form</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= hidden_field_tag 'address[id]', nil %>

        <div class="row">
          <div class="col-4">
            <div class="form-group inline-form-toggle">
              <%= label_tag '', class: 'switch' do %>
                <%= check_box_tag 'addressable[is_business_address]' %>
                <span class="slider round"></span>
              <% end %>

              <%= label_tag 'addressable[is_business_address]', 'Business Address' %>
            </div>
          </div>
          <div class="col-4">
            <div class="form-group inline-form-toggle">
              <%= label_tag '', class: 'switch' do %>
                <%= check_box_tag 'addressable[is_home_address]' %>
                <span class="slider round"></span>
              <% end %>

              <%= label_tag 'addressable[is_home_address]', 'Home Address' %>
            </div>
          </div>
          <div class="col-4">
            <div class="form-group inline-form-toggle">
              <%= label_tag '', class: 'switch' do %>
                <%= check_box_tag 'addressable[is_delivery_address]' %>
                <span class="slider round"></span>
              <% end %>

              <%= label_tag 'addressable[is_delivery_address]', 'Delivery Address' %>
            </div>
          </div>

          <div class="col-6">
            <div class="form-group">
              <%= label_tag :contact, 'Contact' %>
              <%= select_tag 'addressable[contact_info]', options_for_select(customer.contact_informations.map { |contact| [contact.name, contact.id] }, selected: nil), { prompt: 'Choose Contact...', class: 'form-control' } %>
            </div>
          </div>

          <div class="col-6">
            <div class="form-group">
              <%= label_tag 'addressable[fax]', 'Fax' %>
              <%= text_field_tag 'addressable[fax]', nil, class: 'form-control', placeholder: 'Fax' %>
            </div>
          </div>

          <div class="col-6">
            <div class="form-group">
              <%= label_tag 'addressable[tax_id]', 'TIN' %>
              <%= text_field_tag 'addressable[tax_id]', nil, class: 'form-control numeric-field', placeholder: 'TIN' %>
            </div>
          </div>

          <div class="col-6 business-section">
            <div class="form-group">
              <%= label_tag 'addressable[business_name]', 'Business Name' %>
              <%= text_field_tag 'addressable[business_name]', nil, id: 'business_name', class: 'form-control', placeholder: 'Business Name' %>
            </div>
          </div>

          <div class="col-6 delivery-schedule-section">
            <div class="form-group">
              <%= label_tag 'addressable[delivery_schedule_day]', 'Delivery Schedule' %>
              <div id="week-picker-delivery_schedule_day"></div>
              <%= hidden_field_tag 'addressable[delivery_schedule_day]', '' %>
            </div>
          </div>
        </div>

        <hr>

        <div class="row">
          <div class="col-12">
            <div class="form-group">
              <%= label_tag 'address[basic_address]', 'Address' %>
              <%= text_field_tag 'address[basic_address]', nil, class: 'form-control', placeholder: 'Address' %>
            </div>
          </div>
          <div class="col-4">
            <div class="form-group">
              <%= label_tag 'address[town_city]', 'Town/City' %>
              <%= text_field_tag 'address[town_city]', nil, class: 'form-control', placeholder: 'Town/City' %>
            </div>
          </div>
          <div class="col-4">
            <div class="form-group">
              <%= label_tag 'address[state_province]', 'State/Province' %>
              <%= text_field_tag 'address[state_province]', nil, class: 'form-control', placeholder: 'State/Province' %>
            </div>
          </div>
          <div class="col-4">
            <div class="form-group">
              <%= label_tag 'address[country]', 'Country' %>
              <%= text_field_tag 'address[country]', nil, class: 'form-control', placeholder: 'Country' %>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

        <%= submit_tag 'Save Changes', id: 'save-address-btn', class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/customers/partials/_basic_information.html.erb
<h4>Basic Information</h4>

<div class="row">
  <div class="col-4">
    <div class="form-group">
      <%= form.label :name, 'Name' %>
      <%= form.text_field :name, class: 'form-control', required: true, placeholder: 'Customer name' %>
    </div>

    <div class="form-group">
      <%= form.label :owner, 'Owner' %>
      <%= form.text_field :owner, id: 'owner', class: 'form-control', placeholder: 'Owner' %>
    </div>

    <div class="form-group">
      <%= form.label :email, 'Email Address' %>
      <%= form.text_field :email, class: 'form-control', placeholder: 'Customer email' %>
    </div>
  </div>

  <div class="col-4">
    <div class="form-group">
      <%= form.label :type_of_receipt, 'Type of Receipt' %>
      <%= form.select(:type_of_receipt, Customer.type_of_receipts.map { |k, v| [k.titleize, v] }, { prompt: 'Select Type of Receipt...', :selected => Customer.type_of_receipts[@customer.type_of_receipt]}, { class: 'form-control' }) %>
    </div>

    <div class="form-group">
      <%= form.label :classification, 'Classification' %>
      <%= form.select(:classification, Customer.classifications.map { |k, v| [k.titleize, v] }, { prompt: 'Select a Customer Classification...', :selected => Customer.classifications[@customer.classification] }, { class: 'form-control' }) %>
    </div>

    <div class="form-group">
      <%= form.label :current_balance, 'Current Balance' %>
      <%= form.text_field :current_balance, class: 'form-control', required: true, placeholder: 'Current Balance', readonly: true %>
    </div>
  </div>

  <div class="col-4">
    <div class="form-group">
      <%= label_tag :salesman, 'Salesman' %>
      <%= select_tag 'customer[salesman_id]', options_for_select(@salesmen.collect { |sm| [sm.contact_information.name, sm.contact_information.id] }, selected: @customer.salesman_id), { prompt: 'Select a Salesman...', class: 'form-control' } %>
    </div>

    <div class="form-group">
      <%= label_tag 'customer[admin_credit_hold]', 'Admin Credit Hold', class: 'font-weight-bold disp-block' %>

      <%= label_tag '', class: 'switch' do %>
        <%= form.check_box :admin_credit_hold, id: 'customer_admin_credit_hold' %>
        <span class="slider round"></span>
      <% end %>
    </div>

    <div class="form-group">
      <%= label_tag 'customer[has_bounced_cheq]', 'Has Bounced Cheque', class: 'font-weight-bold disp-block' %>

      <%= label_tag '', class: 'switch' do %>
        <%= form.check_box :has_bounced_cheq, id: 'customer_has_bounced_cheq' %>
        <span class="slider round"></span>
      <% end %>
    </div>
  </div>
</div>

app/views/customers/partials/_collection_information.html.erb
<h4>Collection Information</h4>

<div class="row">
  <div class="col-4">
    <div class="form-group">
      <%= label_tag :credit_terms, 'Credit Terms' %>
      <%= select_tag 'collection_information[credit_term]', options_for_select(CollectionInformation.credit_terms.map { |k, v| [k.humanize.capitalize, v] }, selected: CollectionInformation.credit_terms[@customer.collection_information.credit_term]), { id: 'ci-credit-terms', class: 'form-control', required: true } %>
    </div>
  </div>

  <div class="col-4">
    <div class="form-group">
      <%= label_tag 'collection_information[credit_limit]', 'Credit Limit' %>
      <%= text_field_tag 'collection_information[credit_limit]', number_to_currency(@customer.collection_information.try(:credit_limit), unit: '', precision: 2), class: 'form-control currency-field', required: true, placeholder: 'Credit Limit' %>
    </div>
  </div>

  <div class="col-4">
    <div class="form-group">
      <%= label_tag :contact, 'Contact' %>
      <%= select_tag 'collection_information[contact_info]', options_for_select(customer.contact_informations.map { |contact| [contact.name, contact.id] }, selected: customer.collection_information.try(:contact).try(:id)), { prompt: 'Choose Contact...', class: 'form-control' } %>
    </div>
  </div>

  <div class="col-6">
    <div class="form-group">
      <%= label_tag 'collection_information[counter_day]', 'Counter day and time' %>

      <%= hidden_field_tag 'collection_information[counter_day]', @customer.collection_information.counter_day %>
      <div class="col-12 no-padding">
        <div class="row">
          <div class="col-6">
            <div id="week-picker-counter_day" class="center-y"></div>
          </div>
          <div class="col-6">
            <div class="row">
              <div class="col-5 time-range-picker">

              <%= text_field_tag 'collection_information[counter_time_from]', @customer.collection_information.get_counter_time.first, class: 'form-control time time-only-picker', required: true %>
              </div>
              <div class="col-5">
                <%= text_field_tag 'collection_information[counter_time_to]', @customer.collection_information.get_counter_time.last, class: 'form-control time time-only-picker', required: true %>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-6">
    <div class="form-group">
      <%= label_tag 'collection_information[collection_day]', 'Collection day and time' %>
      <%= hidden_field_tag 'collection_information[collection_day]', @customer.collection_information.collection_day %>
      <div class="col-12 no-padding">
        <div class="row">
          <div class="col-6">
            <div id="week-picker-collection_day" class="center-y"></div>
          </div>
          <div class="col-6">
            <div class="row">
              <div class="col-5 time-range-picker">

                <%= text_field_tag 'collection_information[collection_time_from]', @customer.collection_information.get_collection_time.first, class: 'form-control time time-only-picker', required: true %>
              </div>
              <div class="col-5">
                <%= text_field_tag 'collection_information[collection_time_to]', @customer.collection_information.get_collection_time.last, class: 'form-control time time-only-picker', required: true %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customers/partials/_form.html.erb
  <hr>

<%= form_with(model: customer, local: true) do |form| %>
  <%= hidden_field_tag 'resource[id]', customer.id %>
  <%= hidden_field_tag 'resource[type]', 'Customer' %>

  <%= render partial: 'shared/partials/form_error', locals: { resource: customer } %>

  <%= render partial: 'customers/partials/form_buttons', locals: { form: form, customer: customer } %>

  <hr>

  <%= render partial: 'customers/partials/basic_information', locals: { form: form } %>

  <hr>

  <%= render partial: 'customers/partials/collection_information', locals: { customer: customer } %>

  <hr>

  <%= render partial: 'shared/partials/addresses', locals: { resource: customer, resource_type: 'Customer', address_resource: CustomerAddress } %>

  <hr>

  <%= render partial: 'shared/partials/discounts', locals: { resource: customer, resource_type: 'Customer' } %>

  <hr>

  <%= render partial: 'shared/partials/contact_informations', locals: { resource: customer, resource_type: 'Customer' } %>

  <hr>

  <%= render partial: 'customers/partials/form_buttons', locals: { form: form, customer: customer } %>

  <%= render partial: 'customers/partials/address_form_modal', locals: { customer: customer } %>
  <%= render partial: 'shared/partials/discount_form_modal', locals: { brands: @brands } %>
  <%= render partial: 'shared/partials/contact_information_form_modal' %>
<% end %>

<script type="text/javascript">
  var brands = "<%= j(@brands.to_json.html_safe) %>";
</script>

app/views/customers/partials/_form_buttons.html.erb
<div class="actions align-right">
  <%= form.submit class: 'btn btn-success' %>
  <%= link_to 'Discard', customer_path(customer, axn: 'discarded'), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } if customer.unsaved? %>
  <%= link_to 'Back', customers_path, class: 'btn btn-outline-secondary' %>
</div>

app/views/customers/partials/_index_buttons.html.erb
<%= link_to 'New Customer', new_customer_path, class: 'btn btn-primary' if policy(Customer).allow_add? %>
<% if policy(Customer).allow_delete? %>
  <button type="button" id="archive-selected" class="btn btn-danger archive-selected">Archive Selected</button>
<% end %>