config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    resources :users do
      collection do
        get 'salesmen'
      end
    end
  end

  root to: 'dashboards#index'

  resources :dashboards
  resources :permissions
  resources :brands
  resources :item_bundles
  resources :discounts
  resources :contact_informations
  resources :return_slips
  resources :order_slips

  resources :attachments, only: [:destroy]

  resources :categories do
    get 'sub_categories'
  end

  resources :items do
    resources :item_inventories do
      collection do
        delete 'delete_by_bulk'
        get 'serials'
        get 'on_stock'
      end
    end

    collection do
      match 'search-available', to: "items#search_available", via: [:get, :post]
      match 'search-return', to: "items#search_return", via: [:get, :post]
      match 'search-sold', to: "items#search_sold", via: [:get, :post]
    end
  end

  resources :warehouses do
    resources :stock_sections
  end

  resources :roles do
    get 'permissions'
    get 'update_permissions'
  end

  resources :addresses do
    member do
      patch 'make_primary'
    end
  end

  resources :customers do
    resources :customer_orders do
      member do
        match 'add-item-to-order', to: "customer_orders#add_item_to", via: [:get, :post]
        match 'deduct-item-from-order', to: "customer_orders#sub_item_from", via: [:delete]
        match 'remove-item-from-order', to: "customer_orders#del_item_from", via: [:delete]
        match 'items-of', to: "customer_orders#items_of", via: [:get, :post]
      end
    end

    member do
      delete 'archive'
    end
  end

  resources :suppliers do
    member do
      get 'delete_selected'
      delete 'archive'
    end
  end

  resources :receivables do
    collection do
      get :add_deductible_entry
      get :add_breakdown
      post :del_breakdown
      post :tpl_switcher
    end
  end
end

app/models/customer_order.rb
	# Notes:
# monetize needs rails-money gem
class CustomerOrder < ApplicationRecord
	include UserAccountable

	# default_scope { order(sale_date: :desc) }

	belongs_to	:customer
	belongs_to	:warehouse
	belongs_to	:sales_person, class_name: 'User', foreign_key: 'salesman_id', optional: true
	belongs_to	:billing_address, class_name: 'CustomerAddress', foreign_key: 'billing_address_id'
	belongs_to	:shipping_address, class_name: 'CustomerAddress', foreign_key: 'shipping_address_id'

	has_many 	:customer_order_items
	has_and_belongs_to_many :customer_order_checkers, class_name: 'User'
	has_many	:customer_order_statuses, -> { order 'created_at desc' }

	monetize 	:net_sales_cents
	monetize 	:gross_sales_cents
	monetize	:net_amount_due_cents

	validates	:trans_ref_number, presence: true, uniqueness: true
	validates :billing_address, :shipping_address, :customer, :warehouse, presence: true, if: :is_saved?

	attr_accessor :destroyed

	after_destroy :mark_as_destroyed

	before_validation	:create_id, :calculate_amount, :fill_missing_fields

	accepts_nested_attributes_for :customer_order_items, allow_destroy: true

	validate :shipping_address_is_delivery_address, if: :is_saved?
	validate :delivery_address_must_have_tax, if: :is_saved?

	def mark_as_destroyed
	  self.destroyed = true
	end

	after_initialize do |order|
		order.doc_data = {
			discounts: []
			} if order.doc_data.nil?
		create_id
	end

	def checker_ids
		self.customer_order_checkers.collect{ |chkr| chkr.id }
	end

	def checker_ids=(ids)
		self.customer_order_checkers = User.find(ids.reject { |id| id.empty? })
	end

	def is_saved?
		self.saved
	end

	private
	def fill_missing_fields
		@sale_date = Time.now if @sale_date.blank?
	end

	def calculate_amount
		gross = 0
		net = 0
		customer_order_items.each do |oi|
			gross += oi.calculate_amount
			net += oi.net_amount
		end

		self.gross_sales = gross
    self.net_sales = net

		# apply non-brand discounts
    self.doc_data["discounts"] = []
		customer.discounts.each do |dc|
			if dc.brand.nil?
				if !dc.bound_by_date || (dc.bound_by_date && dc.within_promo_date(customer_order.sale_date))
					dc.discount.each do |pct|
						self.doc_data["discounts"] << pct.to_f
						net -= (net * (pct.to_f / 100))
					end
				end
			end
		end

		self.net_amount_due = net

		self.gross_sales
	end

	def create_id
		if self.trans_ref_number.blank?
			day_count = CustomerOrder.where(created_at: DateTime.now.beginning_of_day..DateTime.now.end_of_day).count
			self.trans_ref_number = "CO-#{Time.now.to_i}-#{'%03d' % (day_count + 1).to_s(16)}"
		end
	end

	def shipping_address_is_delivery_address
		unless shipping_address.is_delivery_address
			errors.add(:base, 'shipping address is not a valid delivery address')
		end
	end

	def delivery_address_must_have_tax
		unless billing_address.tax_id.present?
			errors.add(:base, 'billing address does not have valid tax information')
		end
	end
end

app/controllers/customer_orders_controller.rb
class CustomerOrdersController < ApplicationController

  before_action :fetch_order
  before_action :set_customer, only: [:index, :new, :show]

	def index
		respond_to do |format|
		    format.html
		    format.json { render json: CustomerOrderDatatable.new(params, view_context: view_context)	 }
		end
	end

	def new
		unsaved = CustomerOrder.where(saved: false, customer: @customer)

		if unsaved.any?
			@customer_order = unsaved.first
		else
			@customer_order = CustomerOrder.create(customer: @customer,
				warehouse: (@customer.user.present? && @customer.user.warehouse.present?) ? @customer.user.warehouse : Warehouse.all.take,
				sales_person: @customer.user.present? ? @customer.user :  current_user,
				billing_address: @customer.customer_addresses.where.not(tax_id: [nil, '']).take,
				shipping_address: @customer.customer_addresses.where(is_business_address: true).take)
		end

		Rails.logger.debug @customer_order.customer.customer_addresses.inspect
	end

	def create; end

	def edit
		respond_to do |format|
			format.html
			format.json { render json: @customer_order }
		end
	end

	def update
		respond_to do |format|
			if @customer_order.update(customer_order_params) && @customer_order.update_attribute(:saved, true)
				format.html { redirect_to customer_customer_orders_path(customer: @customer_order.customer), notice: 'Order was successfully updated.' }
	        	format.json { render :show, status: :ok, location: customer_customer_order_path(customer_order: @customer_order, customer: @customer_order.customer) }
			else
				format.html { render action: :edit }
	        	format.json { render json: @customer_order.errors, status: :unprocessable_entity }
			end
		end
	end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @customer_order }
      format.pdf do
        render pdf: 'naknang_filename',
               layout: 'pdf'
      end
    end
  end

  def destroy
    respond_to do |format|
      if @customer_order.update_attributes(removed: true, removed_at: Time.now)
        format.html { redirect_to action: :index }
        format.json do
          render json: { status: :ok, customer_order: @customer_order }
        end
      else
        format.html do
          redirect_to action: :index, notice: 'Unable to remove Order record.'
        end
        format.json do
          render json: {
            status: :unprocessable_entity,
            receivable: @customer_order
          }
        end
      end
    end
  end

	def add_item_to
		handler = ItemToOrderHandler.execute(params[:item], params[:serial], params[:id], 'add')
		render json: handler.to_json(include: [:order_item, :sales_detail] ), status: handler.result[:status]
	end

  def sub_item_from
    handler = ItemToOrderHandler.execute(params[:item], params[:serial], params[:id], 'sub')
		render json: handler.to_json(include: [:order_item] ), status: handler.result[:status]
  end

  def del_item_from
    handler = ItemToOrderHandler.execute(params[:item], params[:serial], params[:id], 'del')
		render json: handler.to_json(include: [:order_item] ), status: handler.result[:status]
  end

	def items_of
		@customer_order = CustomerOrder.find(params[:id])

		respond_to do |format|
			format.html
			format.json { render json: @customer_order }
			format.js
		end
	end

	private
	def fetch_order
		@customer_order = CustomerOrder.find(params[:id]) if params[:id].present?
	end

  def customer_order_params
    params.require(:customer_order).permit(
      :customer_id,
      :warehouse_id,
      :gross_amount,
      :net_amount,
      :net_amount_due,
      :delivery_date,
      :sale_date,
      :shipping_address_id,
      :billing_address_id,
      :checker_ids => []
    )
  end

  def set_customer
    @customer = Customer.find(params[:customer_id])
  end
end

app/views/customer_orders/partials/_form.html.erb
<h1>Customer Order</h1>

<%= form_with(model: @customer_order, url: [@customer_order.customer, @customer_order], local: true) do |f| %>

<%= render partial: 'shared/partials/form_error', locals: { resource: @customer_order } %>

<table class="table table-borderless customer-details">
  <tbody>
    <tr>
      <td class="cell-label"><%= f.label :customer, 'Customer' %></td>
      <td>
        <%= @customer_order.customer.name %>
      </td>

      <td class="cell-label"><%= f.label :terms, 'Terms' %></td>
      <td>
        <%= @customer_order.customer.collection_information.credit_term.humanize %>
      </td>
    </tr>
    <tr>
      <td class="cell-label"><%= f.label :warehouse, 'Warehouse' %></td>
      <td>
        <%= f.collection_select(:warehouse_id, Warehouse.all, :id, :name, { selected: @customer_order.warehouse_id }, { id: "warehouse-select", class: "form-control" } ) %>
      </td>
      <td class="cell-label"><%= f.label :salesman_id,'PO Reference' %></td>
      <td>
        <%= f.text_field :po_reference, id: "order-po",:class => "form-control"  %>
      </td>
    </tr>
    <tr>
      <td class="cell-label"><%= f.label :billing_address_id, 'Billing Address' %></td>
      <td>
        <%= f.select :billing_address_id, options_for_select( @customer_order.customer.nil? ? [] : @customer_order.customer.customer_addresses.where.not(tax_id: [nil, '']).map { |addr| ["#{addr.tax_id} - #{addr.business_name}", addr.id] }, @customer_order.billing_address_id), { }, { class:  "form-control", id: "billing-address" }  %>
      </td>
      <td class="cell-label"><%= f.label :sale_date, 'Sale Date' %></td>
      <td>
        <div class="form-row">
          <div class="form-group col-md-5"><%= f.text_field :sale_date, id: "order-sale-date",:class => "form-control date-picker-field"  %></div>
        </div>
      </td>
    </tr>
    <tr>
      <td class="cell-label"><%= f.label :shipping_address_id, 'Delivery Address' %></td>
      <td>
        <%= f.select :shipping_address_id, options_for_select( @customer_order.customer.nil? ? [] : @customer_order.customer.customer_addresses.map { |addr| ["#{addr.tax_id} - #{addr.business_name}", addr.id] }, @customer_order.shipping_address_id), { }, { class:  "form-control", id: "shipping-address" }  %>
      </td>
      <td class="cell-label"><%= f.label :delivery_date, 'Delivery Date' %></td>
      <td>
        <div class="form-row">
          <div class="form-group col-md-5"><%= f.text_field :delivery_date, id: "order-delivery-date",:class => "form-control date-picker-field"  %></div>
        </div>
      </td>
    </tr>
    <tr>
      <td class="cell-label"><%= f.label :customer_order_checkers, 'Checked By' %></td>
      <td>
        <%= f.select :checker_ids, ((@customer_order.warehouse.nil? || @customer_order.warehouse.personnels.empty?) ? User.joins(:contact_information).saved : @customer_order.warehouse.personnels.joins(:contact_information)).collect{ |u| [u.contact_information.name, u.id] }, { }, { multiple: true, class:  "form-control select-picker", id: "order-checkers" }  %>
      </td>
      <td class="cell-label"><%= f.label :salesman_id,'Sold By' %></td>
      <td>
        <%= f.select :salesman_id, options_for_select(User.salesmen.saved.collect { |sm| [sm.contact_information.name, sm.id] }), { prompt: 'Select a Salesman...' }, { class: 'form-control', id: 'salesman' } %>
      </td>
    </tr>
    <tr>
      <td colspan="4" style="text-align: right">
        &nbsp;
      </td>
    </tr>
    <tr>
      <td colspan="4" style="text-align: right">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#item-browser"><i class="fa fa-plus"></i> Add Order Item</button>
        <button type="button" class="btn btn-primary" id="sales-invoice-btn"><i class="fa fa-clipboard-list"></i> Sales Invoice</button>
        <button type="button" class="btn btn-primary" id="delivery-rcpt-btn"><i class="fa fa-clipboard-list"></i> Delivery Receipt</button>
        <button type="button" class="btn btn-primary" id="order-sheet-btn"><i class="fa fa-clipboard-list"></i> Order Sheet</button>
        <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Order</button>
        <button type="button" class="btn btn-danger"><i class="fa fa-trash"></i> Delete Order</button>
      </td>
    </tr>
  </tbody>
</table>

<h2>Order List</h2>
<div id="order-item-breakdown">
  <%= render partial: "customer_orders/partials/order_items", locals: { customer_order: @customer_order } %>
</div>

<div class="modal fade" id="item-browser" tabindex="-1" role="dialog" aria-labelledby="item-browser-label" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-xl" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="item-browser-label">Search Item</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="item-add-error-msg">
        </div>
        <form>
          <div class="row">
            <div class="col">
              <input type="text" class="form-control" id="item-keyword" placeholder="Name, Model, SKU or Serial Number Search">
            </div>
          </div>

          <div class="row">&nbsp;</div>

          <div class="row" id="item-selection">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">Stock Qty</th>
                  <th scope="col">SKU</th>
                  <th scope="col">Serial</th>
                  <th scope="col"></th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody id="item-selection-rows">

              </tbody>
            </table>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<% end %>

<%= content_for :inset_scripts do %>
<script type="text/javascript">
let searching = false;
let lastString = '';

//search function simulating fake asynchronous request
const doSearch = function(keyword){
  if(searching) return;

  searching = true;
  lastString = keyword; //remember last string search

  jQuery('.add-inventory-btn').off('click', appendItem);

  jQuery.getJSON(
    "<%= search_available_items_path %>",
    { s: keyword }
  ).done(function(data){
    let tblBody = jQuery('#item-selection-rows');

    tblBody.html('');
    jQuery.each(data.results, (i, inv) => {

      tblBody.append(`
        <tr id="item-${inv.id}-${inv.serial_no}">
          <td>${inv.stock_quantity}</td>
          <td>${inv.sku}</td>
          <td>${inv.serial_no}</td>
          <td>${inv.name}</td>
          <td><a href="#" class="btn btn-primary add-inventory-btn" data-item-id="${inv.id}" data-serial-id="${inv.serial_no}"><i class="fa fa-plus"></i> Add</a></td>
        </tr>
      `);
    });

    jQuery('.add-inventory-btn').on('click', appendItem);
  }).fail((e) => {
    tblBody.html(`
      <tr id="error">
        <td colspan="5">Unable to retrieve data: ${e}</td>
      </tr>
    `);

  }).always(() => {
    jQuery('#item-browser').modal('handleUpdate');

    searching = false;

    const newKeyword = jQuery("#item-keyword").val();
    //search again if string changed
    if( newKeyword !== lastString ){
      doSearch(newKeyword);
    }
  });
};

function disableBtns(){
  //temporarily remove listeners
  jQuery('.add-item-btn, .subtract-item-btn, .remove-item-btn').prop('disabled', true);

  jQuery('.add-item-btn').off('click', appendItem);
  jQuery('.subtract-item-btn').off('click', deductItem);
  jQuery('.remove-item-btn').off('click', removeItem);
}

const enableBtns = function(){
  //return event listeners
  jQuery('.add-item-btn, .subtract-item-btn, .remove-item-btn').prop('disabled', false);

  jQuery('.add-item-btn').on('click', appendItem);
  jQuery('.subtract-item-btn').on('click', deductItem);
  jQuery('.remove-item-btn').on('click', removeItem);

  doSearch( jQuery("#item-keyword").val() );
}

const appendItem = function(){
  let item_id = jQuery(this).data('item-id');
  let serial_id = jQuery(this).data('serial-id');

  jQuery('#item-add-err-msg').html('');

  disableBtns();

  jQuery.getJSON(
    "<%= add_item_to_order_customer_customer_order_path(customer_id: @customer_order.customer.id, id: @customer_order.id) %>",
    { item: item_id, serial: serial_id }
  ).done(function(data){
    let errListEl = jQuery('#item-add-error-msg');
    errListEl.removeClass('alert');
    errListEl.removeClass('alert-danger');

    jQuery.getScript(
      "<%= items_of_customer_customer_order_path(customer_id: @customer_order.customer.id, id: @customer_order.id) %>"
    ).always(enableBtns);

  }).fail((jqxhr) => {
    let errListEl = jQuery('#item-add-error-msg');
    let errorList = jQuery(document.createElement('ul'));
    let resp = JSON.parse(jqxhr.responseText);

    errListEl.addClass('alert alert-danger');

    jQuery.each(resp.result.errors, (err, msg) => {
      errorList.append(`<li>${msg}</li>`);
    });

    errListEl.append(errorList);


  }).always(() => {

  });

  return false;
};

const deductItem = function(){
  let item_id = jQuery(this).data('item-id');
  let serial_id = jQuery(this).data('serial-id');

  jQuery('#item-add-err-msg').html('');

  disableBtns();

  jQuery.getJSON({
    url: "<%= deduct_item_from_order_customer_customer_order_path(customer_id: @customer_order.customer.id, id: @customer_order.id) %>",
    type: 'DELETE',
    dataType: 'json',
    data: { item: item_id, serial: serial_id }
  }).done(function(data){
    let errListEl = jQuery('#item-add-error-msg');
    errListEl.removeClass('alert');
    errListEl.removeClass('alert-danger');

    jQuery.getScript(
      "<%= items_of_customer_customer_order_path(customer_id: @customer_order.customer.id, id: @customer_order.id) %>"
    ).always(enableBtns);

  }).fail((jqxhr) => {
    let errListEl = jQuery('#item-add-error-msg');
    let errorList = jQuery(document.createElement('ul'));
    let resp = JSON.parse(jqxhr.responseText);

    errListEl.addClass('alert alert-danger');

    jQuery.each(resp.result.errors, (err, msg) => {
      errorList.append(`<li>${msg}</li>`);
    });

    errListEl.append(errorList);

  }).always(() => {

  });

  return false;
};

const removeItem = function(){
  let item_id = jQuery(this).data('item-id');
  let serial_id = jQuery(this).data('serial-id');

  jQuery('#item-add-err-msg').html('');

  disableBtns();

  jQuery.ajax({
    url: "<%= remove_item_from_order_customer_customer_order_path(customer_id: @customer_order.customer.id, id: @customer_order.id) %>",
    type: 'DELETE',
    dataType: 'json',
    data: { item: item_id, serial: serial_id }
  }).done(function(data){
    let errListEl = jQuery('#item-add-error-msg');
    errListEl.removeClass('alert');
    errListEl.removeClass('alert-danger');

    jQuery.getScript(
      "<%= items_of_customer_customer_order_path(customer_id: @customer_order.customer.id, id: @customer_order.id) %>"
    ).always(enableBtns);

  }).fail((jqxhr) => {
    let errListEl = jQuery('#item-add-error-msg');
    let errorList = jQuery(document.createElement('ul'));
    let resp = JSON.parse(jqxhr.responseText);

    errListEl.addClass('alert alert-danger');

    jQuery.each(resp.result.errors, (err, msg) => {
      errorList.append(`<li>${msg}</li>`);
    });

    errListEl.append(errorList);

  }).always(() => {

  });

  return false;
};

jQuery(document).ready(function(){
  jQuery('#order-checkers').select2();
  jQuery('#salesman').select2();

  jQuery("#item-keyword").keyup(() => {
    doSearch( jQuery(this).val() );
  });

  jQuery("#item-browser").on('shown.bs.modal', () => {
    doSearch( jQuery("#item-keyword").val() );
  });

  doSearch( jQuery("#item-keyword").val() );
  enableBtns();
});
</script>
<% end %>

app/views/customer_orders/partials/_index_buttons.html.erb
<%= link_to 'New Customer Order', new_customer_customer_order_path, class: 'btn btn-primary' %>

app/views/customer_orders/partials/_order_item.html.erb
<tr>
  <td><i class="fa fa-trash"></i></td>
  <td>
    <%= f.text_field :item_quantity, f.object.sale_details.size, class: "order-item-quantity" %>
  </td>
  <td>Product</td>
  <td>Per Unit</td>
  <td>Net Price</td>
</tr>

app/views/customer_orders/partials/_order_items.html.erb
<table class="table order-item-details">
  
  <thead>
    <tr>
      <th></th>
      <th>Qty</th>
      <th>Product</th>
      <th>Serial</th>
      <th>Brand</th>
      <th>Per Unit</th>
      <th>Net Price</th>
    </tr>
  </thead>
  <tbody>
    <%- customer_order.customer_order_items.each do |coi| %>
      <%- if coi.item.is_identifiable? %>
        <%- coi.sales_details.each_with_index do |isd, i| %>
          <tr>
              <td>
                <button class="btn btn-danger subtract-item-btn" disabled data-item-id="<%= coi.item.id %>" data-serial-id="<%= isd.item_inventory.serial_id %>"><i class="fa fa-trash"></i></button>
              </td>
              <td>
                <div class="form-control"><%= coi.sales_details.size %></div>
              </td>
              <td><%= coi.item.name %></td>
              <td><%= isd.item_inventory.serial_id %></td>
              <td><%= coi.item.brand.present? ? coi.item.brand.name : '--' %></td>
              <td><%= coi.item.price %></td>

              <%- if i == 0 %>
                <td rowspan="<%= coi.sales_details.size %>"><%= coi.net_amount.format %></td>
              <%- end %>
          </tr>
        <%- end %>
      <%- else %>
        <tr>
            <td>
              <button class="btn btn-danger remove-item-btn" disabled data-id="<%= coi.id %>" data-item-id="<%= coi.item.id %>" data-serial-id=""><i class="fa fa-trash"></i></button>
            </td>
            <td>
              <div class="input-group col-md-6">
                <div class="input-group-prepend">
                  <button class="btn btn-primary subtract-item-btn" disabled data-id="<%= coi.id %>" data-item-id="<%= coi.item.id %>" data-serial-id=""><i class="fa fa-minus"></i></button>
                </div>
                <input type="text" disabled class="form-control" size="3" value="<%= coi.sales_details.size %>"></input>
                <div class="input-group-append">
                  <button class="btn btn-primary add-item-btn" disabled data-id="<%= coi.id %>" data-item-id="<%= coi.item.id %>" data-serial-id=""><i class="fa fa-plus"></i></button>
                </div>
              </div>
            </td>
            <td><%= coi.item.name %></td>
            <td>&nbsp;</td>
            <td><%= coi.item.brand.present? ? coi.item.brand.name : '--' %></td>
            <td><%= coi.item.price %></td>
            <td><%= coi.net_amount.format %></td>
        </tr>
      <%- end %>
    <%- end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="2">
        <div class="form-group">
          <label>Gross Amount</label>
          <input type="text" class="form-control" disabled value="<%= customer_order.gross_sales.format %>"
        </div>
      </td>
      <td colspan="3">
        <div class="form-group">
          <label>Net Sales</label>
          <input type="text" class="form-control" disabled value="<%= customer_order.net_sales.format %>"
        </div>
      </td>
      <td colspan="2">
        <div class="form-group">
          <label>Net Amount Due</label>
          <input type="text" class="form-control" disabled value="<%= customer_order.net_amount_due.format %>"
        </div>
      </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
  </tfoot>
</table>