config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    resources :users do
      collection do
        get 'salesmen'
      end
    end
  end

  root to: 'dashboards#index'

  resources :dashboards
  resources :permissions
  resources :brands
  resources :item_bundles
  resources :discounts
  resources :contact_informations
  resources :return_slips
  resources :order_slips

  resources :attachments, only: [:destroy]

  resources :categories do
    get 'sub_categories'
  end

  resources :items do
    resources :item_inventories do
      collection do
        delete 'delete_by_bulk'
        get 'serials'
        get 'on_stock'
      end
    end

    collection do
      match 'search-available', to: "items#search_available", via: [:get, :post]
      match 'search-return', to: "items#search_return", via: [:get, :post]
      match 'search-sold', to: "items#search_sold", via: [:get, :post]
    end
  end

  resources :warehouses do
    resources :stock_sections
  end

  resources :roles do
    get 'permissions'
    get 'update_permissions'
  end

  resources :addresses do
    member do
      patch 'make_primary'
    end
  end

  resources :customers do
    resources :customer_orders do
      member do
        match 'add-item-to-order', to: "customer_orders#add_item_to", via: [:get, :post]
        match 'deduct-item-from-order', to: "customer_orders#sub_item_from", via: [:delete]
        match 'remove-item-from-order', to: "customer_orders#del_item_from", via: [:delete]
        match 'items-of', to: "customer_orders#items_of", via: [:get, :post]
      end
    end

    member do
      delete 'archive'
    end
  end

  resources :suppliers do
    member do
      get 'delete_selected'
      delete 'archive'
    end
  end

  resources :receivables do
    collection do
      get :add_deductible_entry
      get :add_breakdown
      post :del_breakdown
      post :tpl_switcher
    end
  end
end

app/views/receivables/templates/default/_form_deductible.html.erb
<tr class="deductible-row">
  <td class="cell-label">
  	<button class="btn delete-deductible-item"><i class="fa fa-minus-circle"></i></button>
  </td>
  <td><%= text_field_tag "receivable[doc_data][invoice][deductibles][#{index}][name]", deductible['name'], class: "form-control deductible-name" %></td>
  <td>&nbsp;</td>
  <td class="money-cell"><%= text_field_tag "receivable[doc_data][invoice][deductibles][#{index}][value]", deductible['value'], class: "form-control currency-field invoice misc-deductible-value auto-recalculate-all" %></td> 
</tr>

app/views/receivables/templates/default/_receivable_breakdown.html.erb
<%- f.object.data ||= {} %>
<tr class="store-breakdown-item item-<%= f.object.id %>" data-id="<%= f.object.id %>" id="store-breakdown-<%= f.object.id %>">
	<td>
		<a href="#" class="btn edit-breakdown-btn"><i class="fa fa-edit"></i></a>
	</td>
	<td>
		<a href="#" class="btn del-breakdown-btn" data-id="<%= f.object.id %>"><i class="fa fa-trash"></i></a>
	</td>
	<td>
		<span class="business_name"><%= f.object.customer_address.nil? ? '' : f.object.customer_address.business_name %></span>
		<%= f.hidden_field :customer_address_id, class: "store-breakdown customer_address_id" %>
		<%= f.hidden_field :id, id: "breakdown_id", class: "store-breakdown breakdown_id" %>
	</td>
	<td>
		<span class="start_date"><%= f.object.start_date.nil? ? Time.now.strftime('%Y-%m-%d') : f.object.start_date.strftime('%Y-%m-%d') %></span>
		<%= f.hidden_field :start_date, class: "store-breakdown start_date" %>
	</td>
	<td>
		<span class="end_date"><%= f.object.end_date.nil? ? Time.now.strftime('%Y-%m-%d') : f.object.end_date.strftime('%Y-%m-%d') %></span>
		<%= f.hidden_field :end_date, class: "store-breakdown end_date" %>
	</td>
	<td>
		<span class="dept_class"><%= f.object.data['dept_class'].nil? ? "" : f.object.data['dept_class'] %></span>
		<%= hidden_field_tag "receivable[receivable_breakdowns_attributes][#{f.index}][data][dept_class]", f.object.data['dept_class'].nil? ? "" : f.object.data['dept_class'], 
			class: "store-breakdown dept_class"  %>
	</td>
	<td>
		<span class="contract_no"><%= f.object.data['contract_no'].nil? ? "" : f.object.data['contract_no'] %></span>
		<%= hidden_field_tag "receivable[receivable_breakdowns_attributes][#{f.index}][data][contract_no]", f.object.data['contract_no'].nil? ? "" : f.object.data['contract_no'], 
			class: "store-breakdown contract_no"  %>
	</td>
	<td>
		<span class="gross_sales"><%= f.object.gross_sales %></span>
		<%= f.hidden_field :gross_sales, class: "store-breakdown gross_sales currency-field" %>
	</td>
	<td>
		<span class="margin_w_vat"><%= f.object.data['margin_w_vat'].nil? ? "" : f.object.data['margin_w_vat'] %></span>
		<%= hidden_field_tag "receivable[receivable_breakdowns_attributes][#{f.index}][data][margin_w_vat_pct]", f.object.data['margin_w_vat_pct'].nil? ? "" : f.object.data['margin_w_vat_pct'], 
			class: "store-breakdown margin_w_vat_pct percent-field"  %>
		<%= hidden_field_tag "receivable[receivable_breakdowns_attributes][#{f.index}][data][margin_w_vat]", f.object.data['margin_w_vat'].nil? ? "" : f.object.data['margin_w_vat'], 
			class: "store-breakdown margin_w_vat currency-field"  %>
	</td>
	<td>
		<span class="reduced_margin_w_vat"><%= f.object.data['reduced_margin_w_vat'].nil? ? "" : f.object.data['reduced_margin_w_vat'] %></span>
		<%= hidden_field_tag "receivable[receivable_breakdowns_attributes][#{f.index}][data][reduced_margin_w_vat]", f.object.data['reduced_margin_w_vat'].nil? ? "" : f.object.data['reduced_margin_w_vat'], class: "store-breakdown reduced_margin_w_vat currency-field"  %>
	</td>
	<td>
		<span class="vip_discount"><%= f.object.data['vip_discount'].nil? ? "" : f.object.data['vip_discount'] %></span>
		<%= hidden_field_tag "receivable[receivable_breakdowns_attributes][#{f.index}][data][vip_discount]", f.object.data['vip_discount'].nil? ? "" : f.object.data['vip_discount'], 
			class: "store-breakdown vip_discount currency-field"  %>
	</td>
	<td>
		<span class="net_margin"><%= f.object.data['net_margin'].nil? ? "" : f.object.data['net_margin'] %></span>
		<%= hidden_field_tag "receivable[receivable_breakdowns_attributes][#{f.index}][data][net_margin]", f.object.data['net_margin'].nil? ? "" : f.object.data['net_margin'], 
			class: "store-breakdown net_margin currency-field"  %>
	</td>
	<td>
		<span class="net_sales"><%= f.object.net_sales %></span>
		<%= f.hidden_field :net_sales, class: "store-breakdown net_sales" %>
	</td>
	<td>
		<span class="ewt"><%= f.object.data['ewt'].nil? ? "" : f.object.data['ewt'] %></span>
		<%= hidden_field_tag "receivable[receivable_breakdowns_attributes][#{f.index}][data][ewt]", f.object.data['ewt'].nil? ? "" : f.object.data['ewt'], 
			class: "store-breakdown ewt currency-field"  %>
	</td>
	<td>
		<span class="total_deductions"><%= f.object.data['total_deductions'].nil? ? "" : f.object.data['total_deductions'] %></span>
		<%= hidden_field_tag "receivable[receivable_breakdowns_attributes][#{f.index}][data][total_deductions]", f.object.data['total_deductions'].nil? ? "" : f.object.data['total_deductions'], 
			class: "store-breakdown total_deductions currency-field"  %>
	</td>
	<td>
		<span class="net_amount_due"><%= f.object.net_amount_due %></span>
		<%= f.hidden_field :net_amount_due, class: "store-breakdown net_amount_due currency-field" %>
	</td>
</tr>

app/views/receivables/templates/default/_show.html.erb
<h1>Consignment Receivable</h1>

<table class="table consignor-details">
  <tbody>
    <tr>
      <td class="cell-label"><label>Customer</label></td>
      <td>
        <%= @receivable.customer.name %>
      </td>

      <td class="cell-label"><label>Template</label></td>
      <td><%= @receivable.template %></td>
    </tr>
    <tr>
      <td class="cell-label"><label>Tax Type</label></td>
      <td><%= @receivable.doc_data['tax_type'] || 'I6 VAT Exclusive Input Tx 12%' %></td>
      <td class="cell-label"><label>Period</label></td>
      <td>
        <div class="form-row">
          <div class="form-group col-md-5"><%= @receivable.start_date  %></div>
          <div class="form-group col-md-2 align-center"> To </div>
          <div class="form-group col-md-5"><%= @receivable.end_date %></div>
        </div>
      </td>
    </tr>
    <tr>
      <td class="cell-label"><label>TIN Number</label></td>
      <td>
        <%= @receivable.customer_address.tax_id  %>
      </td>
      <td class="cell-label"><label>Processing Date</label></td>
      <td>
        <%= @receivable.process_date %>
      </td>
    </tr>
    <tr>
      <td colspan="4">
        <a href="<%= edit_receivable_path(@receivable.id) %>" class="btn btn-primary btn-lg">Edit</a>
        <a href="<%= receivables_path %>" class="btn btn-danger btn-lg">Back To Listing</a>
      </td>
    </tr>
  </tbody>
</table>

<h2>Liquidation Summary</h2>
<table class="table consigment-details">
  <thead>
    <tr>
      <th>Store</th>
      <th>From Date</th>
      <th>To Date</th>
      <th>Contract No</th>
      <th>Dept/Class</th>
      <th>Gross Sales w/ VAT</th>
      <th>Margin w/ VAT</th>
      <th>Reduced Margin w/ VAT</th>
      <th>VIP Discount</th>
      <th>Net Margin w/ VAT</th>
      <th>Net Sales</th>
      <th>EWT</th>
      <th>Total Deductions</th>
      <th>Net Amount Due</th>
    </tr>
  </thead>
  <tbody>
    <% @receivable.receivable_breakdowns.each do |br| %>
    <tr class="store-breakdown-item">
      <td>
        <span class="business_name"><%= br.customer_address.business_name %></span>
      </td>
      <td>
        <span class="start_date"><%= br.start_date.nil? ? Time.now.strftime('%Y-%m-%d') : br.start_date.strftime('%Y-%m-%d') %></span>
      </td>
      <td>
        <span class="end_date"><%= br.end_date.nil? ? Time.now.strftime('%Y-%m-%d') : br.end_date.strftime('%Y-%m-%d') %></span>
      </td>
      <td>
        <span class="dept_class"><%= br.data['dept_class'].nil? ? "" : br.data['dept_class'] %></span>
      </td>
      <td>
        <span class="contract_no"><%= br.data['contract_no'].nil? ? "" : br.data['contract_no'] %></span>
      </td>
      <td>
        <span class="gross_sales"><%= br.gross_sales.format %></span>
      </td>
      <td>
        <span class="margin_w_vat"><%= Money.new(br.data['margin_w_vat'].nil? ? 0 : br.data['margin_w_vat']).format %></span>
      </td>
      <td>
        <span class="reduced_margin_w_vat"><%= Money.new(br.data['reduced_margin_w_vat'].nil? ? 0 : br.data['reduced_margin_w_vat']).format %></span>
      </td>
      <td>
        <span class="vip_discount"><%= Money.new(br.data['vip_discount'].nil? ? 0 : br.data['vip_discount']).format %></span>
      </td>
      <td>
        <span class="net_margin"><%= Money.new(br.data['net_margin'].nil? ? 0 : br.data['net_margin']).format %></span>
      </td>
      <td>
        <span class="net_sales"><%= br.net_sales.format %></span>
      </td>
      <td>
        <span class="ewt"><%= Money.new(br.data['ewt'].nil? ? 0 : br.data['ewt']).format %></span>
      </td>
      <td>
        <span class="total_deductions"><%= Money.new(br.data['total_deductions'].nil? ? 0 : br.data['total_deductions']).format %></span>
      </td>
      <td>
        <span class="net_amount_due"><%= br.net_amount_due.format %></span>
      </td>
    </tr>
    <% end %>

    <tr class="4x-bot-border" id="breakdown-separator">
      <td colspan="14">&nbsp;</td>
    </tr>
  </tbody>
  <tfoot>
    <%- @receivable.doc_data['total'] = {} if @receivable.doc_data['total'].nil?  %>

    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td><%= @receivable.gross_sales.format %></td>
      <td><%= Money.new(@receivable.doc_data['total']['margin_w_vat']).format %></td>
      <td><%= Money.new(@receivable.doc_data['total']['reduced_margin_w_vat']).format %></td>
      <td><%= Money.new(@receivable.doc_data['total']['vip_discount']).format %></td>
      <td><%= Money.new(@receivable.doc_data['total']['net_margin']).format %></td>
      <td><%= @receivable.net_sales.format %></td>
      <td><%= Money.new(@receivable.doc_data['total']['ewt']).format %></td>
      <td><%= Money.new(@receivable.doc_data['total']['total_deductions']).format %></td>
      <td><%= @receivable.net_amount_due.format %></td>
    </tr>
  </tfoot>
</table>

<%- @receivable.doc_data['invoice'] = {} if @receivable.doc_data['invoice'].nil?  %>

<h2>Liquidation Voucher</h2>
<table class="table consigment-voucher">
  <tbody>
    <tr>
      <td class="cell-label"><label>Sales</label></td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td class="money-cell"><%= @receivable.gross_sales.format %></td>  
    </tr>
    <tr class="2x-bot-border">
      <td class="cell-label"><label>Less Margins</label></td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td class="money-cell"><%= Money.new(@receivable.doc_data['invoice']['margin_w_vat']).format %></td> 
    </tr>
    <tr>
      <td colspan="4">&nbsp;</td>
    </tr>
    <tr class="2x-bot-border">
      <td class="cell-label"><label>Net Sales</label></td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td class="money-cell"><%= @receivable.net_sales.format %></td> 
    </tr>
    <tr>
      <td colspan="4">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="4">Less:</td>
    </tr>
    <tr>
      <td class="cell-label"><label>EWT</label></td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td class="money-cell"><%= Money.new(@receivable.doc_data['invoice']['ewt']).format %></td> 
    </tr>
    <tr>
      <td class="cell-label" colspan="4"><label>Deductions</label></td>
    </tr>

    <%- @receivable.doc_data['invoice']['deductibles'] = {} if @receivable.doc_data['invoice']['deductibles'].nil?  %>
    <%- @receivable.doc_data['invoice']['deductibles'].each do |index, deductible| %>
      <tr class="deductible-row">
        <td class="cell-label">
          &nbsp;
        </td>
        <td><%= deductible['name'] %></td>
        <td>&nbsp;</td>
        <td class="money-cell"><%= Money.new(deductible['value']).format %></td> 
      </tr>
    <% end %>
    
    <tr>
      <td colspan="4" class="4x-bot-border">&nbsp;</td>
    </tr>
    <tr>
      <td class="cell-label" style="font-size: +1"><label>Net Amount Due</label></td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td class="money-cell"><%= @receivable.net_amount_due.format %></td> 
    </tr>
    <tr>
      <td colspan="4">&nbsp;</td>
    </tr>
    <tr>
      <td colspan="4">
        <h2>Invoice Details</h2>
        <table class="table">
          <tbody>
            <tr>
              <td class="cell-label"><label>Sales</label></td>
              <td class="money-cell"><%= Money.new(@receivable.doc_data['invoice']['sales']).format %></td>
            </tr>
            <tr class="2x-bot-border">
              <td class="cell-label"><label>VAT</label></td>
              <td class="money-cell"><%= Money.new(@receivable.doc_data['invoice']['vat']).format %></td>
            </tr>
            <tr class="4x-bot-border">
              <td class="cell-label"><label>Total Sales Invoice</label></td>
              <td class="money-cell"><%= Money.new(@receivable.doc_data['invoice']['total_sales']).format %></td>
            </tr>
          </tbody>
        </table>
      </td>
    </tr>
    <tr>
      <td colspan="4">
        <a href="<%= edit_receivable_path(@receivable.id) %>" class="btn btn-primary btn-lg">Edit</a>
        <a href="<%= receivables_path %>" class="btn btn-danger btn-lg">Back To Listing</a>
      </td>
    </tr>
  </tbody>
</table>

app/views/receivables/templates/default/_store_breakdown.html.erb
<div class="row">
	<%= form_with(model: store_breakdown, local: true) do |f| %>
	<div class="form-group col-sm-12 col-md-6">
		<%= f.label :customer_addresses_id, "Customer Address" %>
		<%= f.collection_select(:customer_addresses_id, @receivable.customer.customer_addresses, :id, :name, class: ["form-control", :store_address, "breakdown-#{store_breakdown.id}"]) %>
	</div>
	<div class="form-group col-sm-12 col-md-6">
		<%= f.label :from_date, "Start Date" %>
		<%= date_select :store_breakdown, :from_date, class: ["form-control", :store_from_date, "breakdown-#{store_breakdown.id}"] %>
	</div>
	<div class="form-group col-sm-12 col-md-6">
		<%= f.label :to_date, "End Date" %>
		<%= date_select :store_breakdown, :to_date, class: ["form-control", :store_to_date, "breakdown-#{store_breakdown.id}"] %>
	</div>
	<div class="form-group col-sm-12 col-md-6">
		<%= f.label :dept_class, "Dept/Class" %>
		<%= text_field_tag "store_breakdown[data][dept_class]", store_breakdown.data['dept_class'], class: ["form-control", :store_dept_class, "breakdown-#{store_breakdown.id}"]  %>
	</div>
	<div class="form-group col-sm-12 col-md-6">
		<%= f.label :contract_no, "Contract No" %>
		<%= text_field_tag "store_breakdown[data][contract_no]", store_breakdown.data['contract_no'], class: ["form-control", :store_contract_no, "breakdown-#{store_breakdown.id}"] %>  %>
	</div>
	<div class="form-group col-sm-12 col-md-6">
		<%= f.label :gross_sales, "Gross Sales" %>
		<%= f.text_field :gross_sales, class: ["form-control", :store_gross_sales, "breakdown-#{store_breakdown.id}"] %>
	</div>
	<div class="form-group col-sm-12 col-md-6">
		<%= f.label :margin_w_vat, "Margin w/ VAT" %>
		<%= text_field_tag "store_breakdown[data][margin_w_vat]", store_breakdown.data['margin_w_vat'], class: ["form-control", :store_margin_w_vat, "breakdown-#{store_breakdown.id}"]  %>
	</div>
	<div class="form-group col-sm-12 col-md-6">
		<%= f.label :reduced_margin_w_vat, "Reduced Margin w/ VAT" %>
		<%= text_field_tag "store_breakdown[data][reduced_margin_w_vat]", store_breakdown.data['reduced_margin_w_vat'], class: ["form-control", :store_reduced_margin_w_vat, "breakdown-#{store_breakdown.id}"]  %>
	</div>
	<div class="form-group col-sm-12 col-md-6">
		<%= f.label :vip_discount, "VIP Discount" %>
		<%= text_field_tag "store_breakdown[data][vip_discount]", store_breakdown.data['vip_discount'], class: ["form-control", :store_vip_discount, "breakdown-#{store_breakdown.id}"]  %>
	</div>
	<div class="form-group col-sm-12 col-md-6">
		<%= f.label :net_margin, "Net Margin" %>
		<%= text_field_tag "store_breakdown[data][net_margin]", store_breakdown.data['net_margin'], class: ["form-control", :store_net_margin, "breakdown-#{store_breakdown.id}"]  %>
	</div>
	<div class="form-group col-sm-12 col-md-6">
		<%= f.label :store_net_sales, "Net Sales" %>
		<%= f.text_field :net_sales, class: ["form-control", :store_net_sales, "breakdown-#{store_breakdown.id}"] %>
	</div>
	<div class="form-group col-sm-12 col-md-6">
		<%= f.label :ewt, "EWT" %>
		<%= text_field_tag "store_breakdown[data][ewt]", store_breakdown.data['ewt'], class: ["form-control", :store_ewt, "breakdown-#{store_breakdown.id}"]  %>
	</div>
	<div class="form-group col-sm-12 col-md-6">
		<%= f.label :total_deductions, "Total Deductions" %>
		<%= text_field_tag "store_breakdown[data][total_deductions]", store_breakdown.data['total_deductions'], class: ["form-control", :store_total_deductions, "breakdown-#{store_breakdown.id}"]  %>
	</div>
	<div class="form-group col-sm-12 col-md-6">
		<%= f.label :net_amount_due, "Net Amount Due" %>
		<%= f.text_field :net_amount_due, class: ["form-control", :store_net_amount_due, "breakdown-#{store_breakdown.id}"] %>
	</div>
	<% end %>
</div>