config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    resources :users do
      collection do
        get 'salesmen'
      end
    end
  end

  root to: 'dashboards#index'

  resources :dashboards
  resources :permissions
  resources :brands
  resources :item_bundles
  resources :discounts
  resources :contact_informations
  resources :return_slips
  resources :order_slips

  resources :attachments, only: [:destroy]

  resources :categories do
    get 'sub_categories'
  end

  resources :items do
    resources :item_inventories do
      collection do
        delete 'delete_by_bulk'
        get 'serials'
        get 'on_stock'
      end
    end

    collection do
      match 'search-available', to: "items#search_available", via: [:get, :post]
      match 'search-return', to: "items#search_return", via: [:get, :post]
      match 'search-sold', to: "items#search_sold", via: [:get, :post]
    end
  end

  resources :warehouses do
    resources :stock_sections
  end

  resources :roles do
    get 'permissions'
    get 'update_permissions'
  end

  resources :addresses do
    member do
      patch 'make_primary'
    end
  end

  resources :customers do
    resources :customer_orders do
      member do
        match 'add-item-to-order', to: "customer_orders#add_item_to", via: [:get, :post]
        match 'deduct-item-from-order', to: "customer_orders#sub_item_from", via: [:delete]
        match 'remove-item-from-order', to: "customer_orders#del_item_from", via: [:delete]
        match 'items-of', to: "customer_orders#items_of", via: [:get, :post]
      end
    end

    member do
      delete 'archive'
    end
  end

  resources :suppliers do
    member do
      get 'delete_selected'
      delete 'archive'
    end
  end

  resources :receivables do
    collection do
      get :add_deductible_entry
      get :add_breakdown
      post :del_breakdown
      post :tpl_switcher
    end
  end
end

app/models/order_slip.rb
class OrderSlip < ApplicationRecord
	include UserAccountable

	has_many :ordered_items

	has_many :items,
		through: :ordered_items,
		foreign_key: :order_slip_id
	belongs_to :warehouse
	belongs_to :orderable, polymorphic: true

	enum status: {
		_new: 0,
    active: 1,
    inactive: 2,
    archived: 3,
    unsaved: 4
	}
end

app/controllers/order_slips_controller.rb
class OrderSlipsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order_slip, only: [:show, :edit, :update, :destroy]
  before_action :set_items, only: [:new, :create, :edit, :update]

  # GET /order_slips
  # GET /order_slips.json
  def index
    @order_slips = OrderSlip.all

    respond_to do |format|
      format.html
      format.json {
        render json: OrderSlipDatatable.new(params, view_context: view_context)
      }
    end
  end

  # GET /order_slips/1
  # GET /order_slips/1.json
  def show
  end

  # GET /order_slips/new
  def new
    @order_slip = OrderSlip.new
  end

  # GET /order_slips/1/edit
  def edit
  end

  # POST /order_slips
  # POST /order_slips.json
  def create
    @order_slip = OrderSlip.new(order_slip_params)

    respond_to do |format|
      items = params[:items]

      if items.uniq.length == items.length
        is_valid = is_breakdown_valid?

        binding.pry

        if is_valid
          @order_slip.status = :_new

          if @order_slip.save
            log_transaction(@order_slip)

            save_breakdown

            format.html { redirect_to @order_slip, notice: 'Item bundle was successfully created.' }
            format.json { render :show, status: :created, location: @order_slip }
          else
            format.html { render :new }
            format.json { render json: @order_slip.errors, status: :unprocessable_entity }
          end
        else
          format.html { render :new }
          format.json { render json: @order_slip.errors, status: :unprocessable_entity }
        end
      else
        @order_slip.errors.add(:base, 'There are duplicate items selected')

        format.html { render :new }
        format.json { render json: @order_slip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_slips/1
  # PATCH/PUT /order_slips/1.json
  def update
    respond_to do |format|
      if @order_slip.update(order_slip_params)
        log_transaction(@order_slip)

        format.html { redirect_to @order_slip, notice: 'Order Slip was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_slip }
      else
        format.html { render :edit }
        format.json { render json: @order_slip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_slips/1
  # DELETE /order_slips/1.json
  def destroy
    @order_slip.destroy

    log_transaction(@order_slip)

    respond_to do |format|
      format.html { redirect_to order_slips_url, notice: 'Order Slip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order_slip
    @order_slip = OrderSlip.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_slip_params
    params.require(:order_slip).permit(:orderable_id, :warehouse_id, :orderable_type)
  end

  def set_items
    @items = Item.saved
  end

  def is_breakdown_valid?
    # check all items' inventories if quantities are valid
    is_valid = true
    invalid_item = { name: '', current: 0, requested: 0 }

    params[:items].each_with_index do |id, i|
      next if id.blank?

      item = Item.find(id)
      quantity = params[:item_quantity][i].to_i

      if item.item_inventories.stock.count < quantity.to_i
        is_valid = false
        @order_slip.errors.add(:base, "Item <strong>#{item.name}</strong> inventories are insufficient. <br /><strong>Current inventory:</strong> #{item.item_inventories.stock.count} <br /><strong>Requested:</strong> #{quantity}")
        break
      end
    end
  end

  def save_breakdown
    @order_slip.ordered_items.destroy_all

    params[:items].each_with_index do |id, i|
      next if id.blank?

      quantity = params[:item_quantity][i]

      ordered_item = OrderedItem.new
      ordered_item.item_id = id
      ordered_item.order_slip = @order_slip
      ordered_item.quantity = quantity

      ordered_item.save

      log_transaction(ordered_item)
    end
  end
end

app/helpers/order_slips_helper.rb
module OrderSlipsHelper
end

app/views/order_slips/edit.html.erb
<div class="container">
	<h2>Editing Order Slip</h2>

	<%= render 'order_slips/partials/form', order_slip: @order_slip %>
</div>

app/views/order_slips/index.html.erb
<h2>Order Slips</h2>

<hr>

<%= render partial: 'order_slips/partials/index_buttons' %>

<hr>

<table id="order-slips-list" class="table table-hover" data-source="<%= order_slips_url(format: :json) %>">
  <thead>
    <tr>
      <th>Customer</th>
      <th>Warehouse</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>

  <tbody></tbody>
</table>

<hr>

<%= render partial: 'order_slips/partials/index_buttons' %>

app/views/order_slips/new.html.erb
<div class="container">
	<h2>New Order Slip</h2>

	<%= render 'order_slips/partials/form', order_slip: @order_slip %>
</div>

app/views/order_slips/show.html.erb
<div class="container">
	<h2>Order Slip Information</h2>

	<hr>

	<div class="row">
    <div class="col-8">
      <div>
        <h6>Customer</h6>
        <p class="font-italic"><%= @order_slip.orderable.name %></p>
      </div>
    </div>

    <div class="col-4">
      <div>
        <h6>Warehouse</h6>
        <p class="font-italic"><%= @order_slip.warehouse.name %></p>
      </div>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-12">
      <h3>Items Breakdown</h3>
    </div>
  </div>

  <div class="row">
    <div class="col-6"><h6>Item Name</h6></div>
    <div class="col-6"><h6>Quantity</h6></div>

    <% @order_slip.ordered_items.each do |ordered| %>
      <div class="col-6"><%= ordered.item.name %></div>
      <div class="col-6"><%= ordered.quantity %></div>
    <% end %>
  </div>

	<hr>

	<%= link_to 'Edit', edit_order_slip_path(@order_slip), class: 'btn btn-primary' %>
	<%= link_to 'Back', order_slips_path, class: 'btn btn-outline-secondary' %>
</div>